name: client_app_example
description: "Example client app for the enterprise core package"
publish_to: 'none'
resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  connectivity_plus: ^7.3.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^13.2.0
  dio: ^5.11.0
  easy_localization: ^3.0.8
  enterprise_core:
    path: ../../packages/enterprise_core
  enterprise_logger:
    path: ../../packages/enterprise_logger
  enterprise_network:
    path: ../../packages/enterprise_network
  enterprise_storage:
    path: ../../packages/enterprise_storage
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  get_it: ^9.2.1
  hive: ^2.2.3
  injectable: ^3.0.0
  internet_connection_checker_plus: ^3.1.1
  permission_handler: ^13.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  build_runner: 2.15.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
